/**
 * Fetches reviews from the Google Places API (New) and writes
 * them to src/data/reviews.js so the static site stays fresh.
 *
 * Required env vars (set in backend/.env or GitHub secrets):
 *   GOOGLE_PLACES_API_KEY  – a key with Places API (New) enabled
 *   GOOGLE_PLACE_ID        – the Place ID for the salon
 *                            (find it at https://developers.google.com/maps/documentation/places/web-service/place-id)
 *
 * The Places API (New) returns at most 5 reviews per request in
 * the Basic tier. Enable the Advanced tier if you need more.
 *
 * Run locally:  node backend/scripts/fetch-reviews.mjs
 * Run via npm:  cd backend && npm run fetch-reviews
 */

import { writeFileSync, readFileSync } from 'fs'
import { fileURLToPath } from 'url'

const API_KEY = process.env.GOOGLE_PLACES_API_KEY
const PLACE_ID = process.env.GOOGLE_PLACE_ID

if (!API_KEY || !PLACE_ID) {
  console.error('Missing GOOGLE_PLACES_API_KEY or GOOGLE_PLACE_ID env vars')
  process.exit(1)
}

const REVIEWS_PATH = new URL('../../src/data/reviews.js', import.meta.url)

// Read the existing file so we can fall back to it on error
const existing = readFileSync(fileURLToPath(REVIEWS_PATH), 'utf8')

// Extract the profileUrl from the existing file (we keep it unchanged)
const profileUrlMatch = existing.match(/profileUrl:\s*'([^']+)'/)
const profileUrl = profileUrlMatch
  ? profileUrlMatch[1]
  : `https://www.google.com/maps/place/?q=place_id:${PLACE_ID}`

async function fetchPlaceDetails() {
  const fields = ['rating', 'user_ratings_total', 'reviews'].join(',')
  const url = `https://maps.googleapis.com/maps/api/place/details/json?place_id=${PLACE_ID}&fields=${fields}&key=${API_KEY}&language=en&reviews_sort=newest`

  const res = await fetch(url)
  if (!res.ok) throw new Error(`Places API HTTP ${res.status}`)
  const json = await res.json()

  if (json.status !== 'OK') throw new Error(`Places API status: ${json.status} – ${json.error_message ?? ''}`)
  return json.result
}

async function fetchPlaceDetailsBg() {
  const url = `https://maps.googleapis.com/maps/api/place/details/json?place_id=${PLACE_ID}&fields=reviews&key=${API_KEY}&language=bg&reviews_sort=newest`
  const res = await fetch(url)
  if (!res.ok) return []
  const json = await res.json()
  return json.result?.reviews ?? []
}

try {
  const [detailsEn, reviewsBg] = await Promise.all([fetchPlaceDetails(), fetchPlaceDetailsBg()])

  const rating = detailsEn.rating ?? 5.0
  const totalCount = detailsEn.user_ratings_total ?? 0
  const reviewsEn = detailsEn.reviews ?? []

  // Build a map of BG review text keyed by author name for merging
  const bgByAuthor = Object.fromEntries(reviewsBg.map(r => [r.author_name, r.text]))

  const reviews = reviewsEn.map((r, i) => ({
    id: String(i + 1),
    name: r.author_name,
    rating: r.rating,
    text: {
      en: r.text,
      bg: bgByAuthor[r.author_name] ?? r.text,
    },
    date: new Date(r.time * 1000).toISOString().split('T')[0],
  }))

  const output = `// Auto-generated by backend/scripts/fetch-reviews.mjs — do not edit manually
export const googleReviews = ${JSON.stringify({ rating, totalCount, profileUrl, reviews }, null, 2)}
`

  writeFileSync(fileURLToPath(REVIEWS_PATH), output, 'utf8')
  console.log(`✓ Updated reviews.js — rating: ${rating}, count: ${totalCount}, reviews fetched: ${reviews.length}`)
} catch (err) {
  console.error('Failed to fetch reviews:', err.message)
  console.error('Keeping existing reviews.js unchanged.')
  // Don't exit 1 — a failure here should not block CI/CD
}
